[[schedule]]
gacha_id = 1001
gacha_type = 1
gacha_schedule_id = 1001001
begin_time = 1717604747
end_time = 4102441199
gacha_materials = [ { id = 110, count = 1 } ]

[[schedule]]
gacha_id = 2001
gacha_type = 2
gacha_schedule_id = 2001023
up_item_id_list = [1371]
optional_up_item_id_list = [1421, 1351]
begin_time = 1717604747
end_time = 4102441199
gacha_materials = [ { id = 111, count = 1 } ]

[[schedule]]
gacha_id = 2011
gacha_type = 2
gacha_schedule_id = 2001024
up_item_id_list = [1391]
optional_up_item_id_list = [1061, 1121]
begin_time = 1717604747
end_time = 4102441199
gacha_materials = [ { id = 111, count = 1 } ]