["CNBetaWin2.1.1"]
dispatch_seed = "e7fd6332dd8132f3"
design_data_url = "https://autopatchcn.juequling.com/design_data/beta_live/output_8725866_a14df1083f/client/"
design_data_revision = "8725866"
design_data_files = '[{"fileName": "data_version", "fileSize": 4726, "fileMD5": "15094760296626596820"}]'
game_res_url = "https://autopatchcn.juequling.com/game_res/beta_live/output_8725866_a14df1083f/client/"
game_res_branch = "beta_live"
game_audio_revision = "8691934"
game_res_revision = "8725866"
game_res_files = '[{"fileName": "res_version", "fileSize": 2246393, "fileMD5": "9380643846772258099"}, {"fileName": "audio_version", "fileSize": 30436, "fileMD5": "7835339550429636468"}, {"fileName": "base_revision", "fileSize": 18, "fileMD5": "2909015621192464679"}]'
silence_url = "https://autopatchcn.juequling.com/design_data/beta_live/output_8725866_a14df1083f/client_silence/"
silence_revision = "8712238"
silence_files = '[{"fileName": "silence_version", "fileSize": 641, "fileMD5": "13624990639352622230"}]'